name: Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18.x

      - name: Generate wasm file
        run: |
          GOARCH=wasm GOOS=js go build -o main.wasm main.go

      - name: Prepare resource for github pages
        run: |
          mv main.wasm main.wasm.new
          mv index.html index.html.new
          git checkout gh-pages
          mv main.wasm.new main.wasm
          mv index.html.new index.html

      - name: Publish github pages
        uses: EndBug/add-and-commit@v9
        with:
          author_name: bilal-lambda
          author_email: bilalh@lambdatest.com
          message: 'sync main.wasm and index.html'
          add: main.wasm index.html
