name: Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18.x

      - name: Generate wasm file
        run: |
          GOARCH=wasm GOOS=js go build -o main.wasm main.go

      - name: Publish github pages
        run: |
          mv main.wasm main.wasm.new
          git config --global user.email bilalh@lambdatest.com
          git config --global user.name bilal-lambda
          git checkout gh-pages
          mv main.wasm.new main.wasm
          git add main.wasm
          git commit -m "sync main.wasm"
          git push https://${{ github.TOKEN }}@github.com/bilal-lambda/validator-poc/ gh-pages
